name: Go Built and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cache-ci:
    runs-on: ubuntu-latest
    name: caching
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
